hafas-bin6-format: Disable -Wattributes for HafasBin6 structs
This fixes warnings like

hafas-bin6-format.h:44:13: error: packed attribute causes inefficient alignment for 'version' [-Werror=attributes]

on arm. Since we do need this layout there's little we can do about it.